# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    environment:
      - CGO_CFLAGS_ALLOW: ".*"
    steps:
      - checkout
      - run: sudo apt install -y libxmlsec1-dev
      - run: go get ./spidsaml/
      - run: go test -race ./spidsaml/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build